basePath: /api
definitions:
  api.AuthRequest:
    properties:
      email:
        example: john@example.com
        type: string
      name:
        example: John Doe
        minLength: 3
        type: string
      password:
        example: "123456"
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  api.AuthResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      user:
        properties:
          email:
            example: john@example.com
            type: string
          id:
            example: 1
            type: integer
          name:
            example: John Doe
            type: string
        type: object
    type: object
  api.LoginRequest:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: "123456"
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API para gerenciamento de freelancers e projetos
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CRM Freela API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Autentica um usuário no sistema
      parameters:
      - description: Credenciais do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.AuthResponse'
        "400":
          description: Dados inválidos
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Credenciais inválidas
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno
          schema:
            additionalProperties: true
            type: object
      summary: Login de usuário
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Renova o token JWT do usuário
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Token inválido
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Renovar token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registra um novo usuário no sistema
      parameters:
      - description: Dados do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.AuthRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.AuthResponse'
        "400":
          description: Dados inválidos
          schema:
            additionalProperties: true
            type: object
        "409":
          description: E-mail já cadastrado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno
          schema:
            additionalProperties: true
            type: object
      summary: Registrar novo usuário
      tags:
      - auth
  /user/profile:
    get:
      consumes:
      - application/json
      description: Retorna os dados do perfil do usuário autenticado
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Não autorizado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Obter perfil do usuário
      tags:
      - user
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
